name: 'my first container action'
description: 'A cloud guru lab'
author: 'Hannu Piki'
inputs:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome stuff'
  outputs:
    myOutput:
      description: 'total memory'
  runs:
    using: 'docker'
    image: 'Dockerfile'
